
;interface AssociativeArray<RangeType> { [key: string]: RangeType; }

//
 /*\ \**/ /**\ \**/ /**\ \**/ /**\ \**/ /**\ \**/ /**\ \**/ /**\ \**/ /**\ \**/
//

((()=>{ ////
        const veracity= true; const falsity= false; veracity; falsity;
        const set_timeout= (ms :number
                        )=>(fn :(d :any)=>any, ...args :any[]
                        )=> setTimeout(fn, ms, ...args);
              set_timeout(0)(()=> { // unnecessary
//

;;interface Obje { [key :string] :any; };
  const globje= ( ()=>{ } ).constructor('return this;')() as Obje;

 /*\ \**/ /**\ \**/ /**\ \**/

  globje['NML11th_setTimeout']= set_timeout;

//
});
              set_timeout(666)(()=>{ // TODO= something
//

  console.log('OK :-)');

//
});

//
})());

//
 /*\ \**/ /**\ \**/ /**\ \**/ /**\ \**/ /**\ \**/ /**\ \**/ /**\ \**/ /**\ \**/
//

